toolbar1: styleselect | bold italic | link image | undo redo | insert | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image table | fullscreen
#toolbar2: table | fullscreen
plugins:
  - image
  - link
  - table
  - fullscreen
